-- JUANELOS · Esquema completo e idempotente
-- Ejecutar este archivo completo en el SQL Editor de Supabase.
-- No usa Supabase Auth: usuarios, contraseñas y sesiones viven en staff_users/admin_sessions.

create extension if not exists pgcrypto;

create table if not exists public.products (
  id text primary key,
  name text not null,
  category text not null,
  price integer not null check (price >= 0),
  image_url text not null default '',
  description text not null default '',
  badge text not null default '',
  featured boolean not null default false,
  available boolean not null default true,
  sort_order integer not null default 0,
  modifiers jsonb not null default '[]'::jsonb check (jsonb_typeof(modifiers) = 'array'),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.toppings (
  id text primary key,
  name text not null,
  kind text not null check (kind in ('Topping', 'Salsa')),
  price integer not null default 0 check (price >= 0),
  available boolean not null default true,
  sort_order integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.payment_methods (
  id text primary key,
  name text not null,
  account_value text not null default '',
  instructions text not null default '',
  available boolean not null default true,
  sort_order integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.neighborhoods (
  id text primary key,
  name text not null unique,
  delivery_fee integer not null default 0 check (delivery_fee >= 0),
  available boolean not null default true,
  sort_order integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.staff_users (
  id uuid primary key default gen_random_uuid(),
  username text not null,
  display_name text not null,
  password_hash text not null,
  role text not null default 'usuario' check (role in ('jefe', 'usuario')),
  permissions jsonb not null default '{}'::jsonb check (jsonb_typeof(permissions) = 'object'),
  active boolean not null default true,
  created_by uuid references public.staff_users(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  last_login_at timestamptz
);

create unique index if not exists staff_users_username_lower_idx on public.staff_users (lower(username));
create unique index if not exists staff_users_single_boss_idx on public.staff_users (role) where role = 'jefe';

create table if not exists public.admin_sessions (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references public.staff_users(id) on delete cascade,
  token_hash text not null unique,
  expires_at timestamptz not null,
  created_at timestamptz not null default now()
);

create table if not exists public.audit_log (
  id bigint generated by default as identity primary key,
  user_id uuid references public.staff_users(id) on delete set null,
  user_name text not null default 'Sistema',
  action text not null,
  entity text not null,
  entity_id text not null default '',
  details jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

-- Canal ligero de eventos: no almacena órdenes ni credenciales. Solamente
-- despierta al administrador para que lea la versión nueva desde Google Sheets.
create table if not exists public.order_events (
  id bigint generated by default as identity primary key,
  order_id text not null,
  revision bigint not null default 0,
  event_kind text not null default 'changed' check (event_kind in ('created', 'changed', 'deleted')),
  created_at timestamptz not null default now()
);

create index if not exists admin_sessions_lookup_idx on public.admin_sessions (token_hash, expires_at);
create index if not exists audit_log_created_idx on public.audit_log (created_at desc);
create index if not exists order_events_created_idx on public.order_events (created_at desc);
create index if not exists products_sort_idx on public.products (sort_order, name);
create index if not exists toppings_sort_idx on public.toppings (kind, sort_order, name);
create index if not exists neighborhoods_sort_idx on public.neighborhoods (sort_order, name);

create or replace function public.touch_updated_at()
returns trigger
language plpgsql
set search_path = public
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists products_touch_updated_at on public.products;
create trigger products_touch_updated_at before update on public.products
for each row execute function public.touch_updated_at();
drop trigger if exists toppings_touch_updated_at on public.toppings;
create trigger toppings_touch_updated_at before update on public.toppings
for each row execute function public.touch_updated_at();
drop trigger if exists payment_methods_touch_updated_at on public.payment_methods;
create trigger payment_methods_touch_updated_at before update on public.payment_methods
for each row execute function public.touch_updated_at();
drop trigger if exists neighborhoods_touch_updated_at on public.neighborhoods;
create trigger neighborhoods_touch_updated_at before update on public.neighborhoods
for each row execute function public.touch_updated_at();
drop trigger if exists staff_users_touch_updated_at on public.staff_users;
create trigger staff_users_touch_updated_at before update on public.staff_users
for each row execute function public.touch_updated_at();

alter table public.products enable row level security;
alter table public.toppings enable row level security;
alter table public.payment_methods enable row level security;
alter table public.neighborhoods enable row level security;
alter table public.staff_users enable row level security;
alter table public.admin_sessions enable row level security;
alter table public.audit_log enable row level security;
alter table public.order_events enable row level security;

drop policy if exists storefront_read_products on public.products;
create policy storefront_read_products on public.products for select to anon using (true);
drop policy if exists storefront_read_toppings on public.toppings;
create policy storefront_read_toppings on public.toppings for select to anon using (true);
drop policy if exists storefront_read_payments on public.payment_methods;
create policy storefront_read_payments on public.payment_methods for select to anon using (true);
drop policy if exists storefront_read_neighborhoods on public.neighborhoods;
create policy storefront_read_neighborhoods on public.neighborhoods for select to anon using (true);
drop policy if exists realtime_read_order_events on public.order_events;
create policy realtime_read_order_events on public.order_events for select to anon using (true);

create or replace function public.publish_order_event(p_order_id text, p_revision bigint, p_event_kind text default 'changed')
returns boolean
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.order_events(order_id, revision, event_kind)
  values(left(coalesce(p_order_id, ''), 80), greatest(coalesce(p_revision, 0), 0),
    case when p_event_kind in ('created', 'changed', 'deleted') then p_event_kind else 'changed' end);
  delete from public.order_events where created_at < now() - interval '24 hours';
  return true;
end;
$$;

create or replace function public.session_user_id(p_token text)
returns uuid
language sql
stable
security definer
set search_path = public, extensions
as $$
  select u.id
  from public.admin_sessions s
  join public.staff_users u on u.id = s.user_id
  where s.token_hash = encode(digest(coalesce(p_token, ''), 'sha256'), 'hex')
    and s.expires_at > now()
    and u.active
  limit 1;
$$;

create or replace function public.user_has_permission(p_user_id uuid, p_permission text)
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1 from public.staff_users u
    where u.id = p_user_id and u.active
      and (u.role = 'jefe' or coalesce((u.permissions ->> p_permission)::boolean, false))
  );
$$;

create or replace function public.bootstrap_status()
returns jsonb
language sql
stable
security definer
set search_path = public
as $$
  select jsonb_build_object('hasBoss', exists(select 1 from public.staff_users where role = 'jefe'));
$$;

create or replace function public.create_initial_boss(
  p_username text,
  p_display_name text,
  p_password text
)
returns jsonb
language plpgsql
security definer
set search_path = public, extensions
as $$
declare
  v_user public.staff_users;
  v_token text := encode(gen_random_bytes(32), 'hex');
begin
  if exists(select 1 from public.staff_users where role = 'jefe') then
    raise exception 'El jefe ya fue creado.';
  end if;
  if length(trim(p_username)) < 3 or length(p_password) < 8 or length(trim(p_display_name)) < 2 then
    raise exception 'Completa un usuario válido, nombre y contraseña de mínimo 8 caracteres.';
  end if;

  insert into public.staff_users (username, display_name, password_hash, role, permissions)
  values (
    lower(trim(p_username)), trim(p_display_name), crypt(p_password, gen_salt('bf', 10)), 'jefe',
    '{"products":true,"toppings":true,"payments":true,"neighborhoods":true,"orders":true,"users":true,"audit":true}'::jsonb
  ) returning * into v_user;

  insert into public.admin_sessions (user_id, token_hash, expires_at)
  values (v_user.id, encode(digest(v_token, 'sha256'), 'hex'), now() + interval '12 hours');
  insert into public.audit_log (user_id, user_name, action, entity, entity_id)
  values (v_user.id, v_user.display_name, 'crear_jefe', 'usuario', v_user.id::text);

  return jsonb_build_object('token', v_token, 'user', jsonb_build_object(
    'id', v_user.id, 'username', v_user.username, 'displayName', v_user.display_name,
    'role', v_user.role, 'permissions', v_user.permissions
  ));
exception when unique_violation then
  raise exception 'El usuario o el jefe ya existe.';
end;
$$;

create or replace function public.admin_login(p_username text, p_password text)
returns jsonb
language plpgsql
security definer
set search_path = public, extensions
as $$
declare
  v_user public.staff_users;
  v_token text := encode(gen_random_bytes(32), 'hex');
begin
  select * into v_user from public.staff_users
  where lower(username) = lower(trim(p_username)) and active limit 1;
  if v_user.id is null or crypt(p_password, v_user.password_hash) <> v_user.password_hash then
    raise exception 'Usuario o contraseña incorrectos.';
  end if;

  delete from public.admin_sessions where expires_at <= now();
  insert into public.admin_sessions (user_id, token_hash, expires_at)
  values (v_user.id, encode(digest(v_token, 'sha256'), 'hex'), now() + interval '12 hours');
  update public.staff_users set last_login_at = now() where id = v_user.id;
  insert into public.audit_log (user_id, user_name, action, entity, entity_id)
  values (v_user.id, v_user.display_name, 'iniciar_sesion', 'sesion', v_user.id::text);

  return jsonb_build_object('token', v_token, 'user', jsonb_build_object(
    'id', v_user.id, 'username', v_user.username, 'displayName', v_user.display_name,
    'role', v_user.role, 'permissions', v_user.permissions
  ));
end;
$$;

create or replace function public.admin_logout(p_token text)
returns boolean
language plpgsql
security definer
set search_path = public, extensions
as $$
begin
  delete from public.admin_sessions
  where token_hash = encode(digest(coalesce(p_token, ''), 'sha256'), 'hex');
  return true;
end;
$$;

create or replace function public.validate_admin_session(p_token text, p_permission text default null)
returns jsonb
language plpgsql
stable
security definer
set search_path = public, extensions
as $$
declare
  v_id uuid := public.session_user_id(p_token);
  v_user public.staff_users;
begin
  if v_id is null then return jsonb_build_object('valid', false); end if;
  select * into v_user from public.staff_users where id = v_id;
  if p_permission is not null and not public.user_has_permission(v_id, p_permission) then
    return jsonb_build_object('valid', false, 'reason', 'permission');
  end if;
  return jsonb_build_object('valid', true, 'user', jsonb_build_object(
    'id', v_user.id, 'username', v_user.username, 'displayName', v_user.display_name,
    'role', v_user.role, 'permissions', v_user.permissions
  ));
end;
$$;

create or replace function public.admin_snapshot(p_token text)
returns jsonb
language plpgsql
stable
security definer
set search_path = public
as $$
declare
  v_id uuid := public.session_user_id(p_token);
  v_is_boss boolean;
begin
  if v_id is null then raise exception 'Sesión vencida.'; end if;
  select role = 'jefe' into v_is_boss from public.staff_users where id = v_id;
  return jsonb_build_object(
    'products', (select coalesce(jsonb_agg(to_jsonb(p) order by p.sort_order, p.name), '[]') from public.products p),
    'toppings', (select coalesce(jsonb_agg(to_jsonb(t) order by t.kind, t.sort_order, t.name), '[]') from public.toppings t),
    'payments', (select coalesce(jsonb_agg(to_jsonb(m) order by m.sort_order, m.name), '[]') from public.payment_methods m),
    'neighborhoods', (select coalesce(jsonb_agg(to_jsonb(n) order by n.sort_order, n.name), '[]') from public.neighborhoods n),
    'users', case when v_is_boss then (select coalesce(jsonb_agg(jsonb_build_object(
      'id', u.id, 'username', u.username, 'displayName', u.display_name, 'role', u.role,
      'permissions', u.permissions, 'active', u.active, 'createdAt', u.created_at, 'lastLoginAt', u.last_login_at
    ) order by u.role, u.display_name), '[]') from public.staff_users u) else '[]'::jsonb end
  );
end;
$$;

create or replace function public.admin_mutate(p_token text, p_entity text, p_action text, p_data jsonb)
returns jsonb
language plpgsql
security definer
set search_path = public, extensions
as $$
declare
  v_user_id uuid := public.session_user_id(p_token);
  v_user_name text;
  v_permission text;
  v_id text := coalesce(nullif(trim(p_data ->> 'id'), ''), encode(digest(random()::text || clock_timestamp()::text, 'sha256'), 'hex'));
begin
  v_permission := case p_entity
    when 'product' then 'products' when 'topping' then 'toppings'
    when 'payment' then 'payments' when 'neighborhood' then 'neighborhoods' else null end;
  if v_user_id is null or v_permission is null or not public.user_has_permission(v_user_id, v_permission) then
    raise exception 'No tienes permiso para realizar esta acción.';
  end if;
  select display_name into v_user_name from public.staff_users where id = v_user_id;

  if p_action = 'delete' then
    if p_entity = 'product' then delete from public.products where id = v_id;
    elsif p_entity = 'topping' then delete from public.toppings where id = v_id;
    elsif p_entity = 'payment' then delete from public.payment_methods where id = v_id;
    elsif p_entity = 'neighborhood' then delete from public.neighborhoods where id = v_id;
    end if;
  elsif p_action = 'save' then
    if p_entity = 'product' then
      insert into public.products (id,name,category,price,image_url,description,badge,featured,available,sort_order,modifiers)
      values (v_id, trim(p_data->>'name'), trim(p_data->>'category'), (p_data->>'price')::integer,
        coalesce(p_data->>'image_url',''), coalesce(p_data->>'description',''), coalesce(p_data->>'badge',''),
        coalesce((p_data->>'featured')::boolean,false), coalesce((p_data->>'available')::boolean,true),
        coalesce((p_data->>'sort_order')::integer,0), coalesce(p_data->'modifiers','[]'::jsonb))
      on conflict (id) do update set name=excluded.name, category=excluded.category, price=excluded.price,
        image_url=excluded.image_url, description=excluded.description, badge=excluded.badge,
        featured=excluded.featured, available=excluded.available, sort_order=excluded.sort_order, modifiers=excluded.modifiers;
    elsif p_entity = 'topping' then
      insert into public.toppings (id,name,kind,price,available,sort_order)
      values (v_id,trim(p_data->>'name'),p_data->>'kind',coalesce((p_data->>'price')::integer,0),coalesce((p_data->>'available')::boolean,true),coalesce((p_data->>'sort_order')::integer,0))
      on conflict (id) do update set name=excluded.name,kind=excluded.kind,price=excluded.price,available=excluded.available,sort_order=excluded.sort_order;
    elsif p_entity = 'payment' then
      insert into public.payment_methods (id,name,account_value,instructions,available,sort_order)
      values (v_id,trim(p_data->>'name'),coalesce(p_data->>'account_value',''),coalesce(p_data->>'instructions',''),coalesce((p_data->>'available')::boolean,true),coalesce((p_data->>'sort_order')::integer,0))
      on conflict (id) do update set name=excluded.name,account_value=excluded.account_value,instructions=excluded.instructions,available=excluded.available,sort_order=excluded.sort_order;
    elsif p_entity = 'neighborhood' then
      insert into public.neighborhoods (id,name,delivery_fee,available,sort_order)
      values (v_id,trim(p_data->>'name'),coalesce((p_data->>'delivery_fee')::integer,0),coalesce((p_data->>'available')::boolean,true),coalesce((p_data->>'sort_order')::integer,0))
      on conflict (id) do update set name=excluded.name,delivery_fee=excluded.delivery_fee,available=excluded.available,sort_order=excluded.sort_order;
    end if;
  else
    raise exception 'Acción no válida.';
  end if;

  insert into public.audit_log (user_id,user_name,action,entity,entity_id,details)
  values (v_user_id,v_user_name,p_action,p_entity,v_id,p_data - 'password');
  return jsonb_build_object('ok',true,'id',v_id);
end;
$$;

create or replace function public.admin_create_user(
  p_token text, p_username text, p_display_name text, p_password text, p_permissions jsonb
)
returns jsonb
language plpgsql
security definer
set search_path = public, extensions
as $$
declare
  v_creator uuid := public.session_user_id(p_token);
  v_creator_name text;
  v_is_boss boolean;
  v_user public.staff_users;
begin
  select role = 'jefe' into v_is_boss from public.staff_users where id = v_creator;
  if v_creator is null or not coalesce(v_is_boss, false) then raise exception 'Solo el jefe puede crear usuarios.'; end if;
  if length(trim(p_username)) < 3 or length(p_password) < 8 or length(trim(p_display_name)) < 2 then raise exception 'Datos de usuario incompletos.'; end if;
  select display_name into v_creator_name from public.staff_users where id=v_creator;
  insert into public.staff_users(username,display_name,password_hash,role,permissions,created_by)
  values(lower(trim(p_username)),trim(p_display_name),crypt(p_password,gen_salt('bf',10)),'usuario',coalesce(p_permissions,'{}'::jsonb),v_creator)
  returning * into v_user;
  insert into public.audit_log(user_id,user_name,action,entity,entity_id,details)
  values(v_creator,v_creator_name,'crear','usuario',v_user.id::text,jsonb_build_object('username',v_user.username,'permissions',v_user.permissions));
  return jsonb_build_object('id',v_user.id,'username',v_user.username,'displayName',v_user.display_name,'permissions',v_user.permissions);
exception when unique_violation then raise exception 'Ese nombre de usuario ya existe.';
end;
$$;

create or replace function public.admin_set_user_active(p_token text, p_user_id uuid, p_active boolean)
returns boolean
language plpgsql
security definer
set search_path = public
as $$
declare v_actor uuid := public.session_user_id(p_token); v_name text; v_is_boss boolean;
begin
  select role = 'jefe' into v_is_boss from public.staff_users where id = v_actor;
  if v_actor is null or not coalesce(v_is_boss, false) then raise exception 'Solo el jefe puede administrar usuarios.'; end if;
  if exists(select 1 from public.staff_users where id=p_user_id and role='jefe') then raise exception 'El jefe no puede desactivarse.'; end if;
  select display_name into v_name from public.staff_users where id=v_actor;
  update public.staff_users set active=p_active where id=p_user_id;
  if not p_active then delete from public.admin_sessions where user_id=p_user_id; end if;
  insert into public.audit_log(user_id,user_name,action,entity,entity_id,details) values(v_actor,v_name,'cambiar_estado','usuario',p_user_id::text,jsonb_build_object('active',p_active));
  return true;
end;
$$;

create or replace function public.admin_reset_user_password(p_token text, p_user_id uuid, p_password text)
returns boolean
language plpgsql
security definer
set search_path = public, extensions
as $$
declare v_actor uuid := public.session_user_id(p_token); v_name text; v_is_boss boolean;
begin
  select role = 'jefe' into v_is_boss from public.staff_users where id = v_actor;
  if v_actor is null or not coalesce(v_is_boss, false) then raise exception 'Solo el jefe puede cambiar contraseñas.'; end if;
  if length(p_password)<8 then raise exception 'La contraseña debe tener mínimo 8 caracteres.'; end if;
  select display_name into v_name from public.staff_users where id=v_actor;
  update public.staff_users set password_hash=crypt(p_password,gen_salt('bf',10)) where id=p_user_id;
  delete from public.admin_sessions where user_id=p_user_id;
  insert into public.audit_log(user_id,user_name,action,entity,entity_id) values(v_actor,v_name,'cambiar_clave','usuario',p_user_id::text);
  return true;
end;
$$;

revoke all on public.staff_users, public.admin_sessions, public.audit_log, public.order_events from anon, authenticated;
grant select on public.products, public.toppings, public.payment_methods, public.neighborhoods, public.order_events to anon, authenticated;
revoke all on function public.session_user_id(text) from public;
revoke all on function public.user_has_permission(uuid,text) from public;
grant execute on function public.bootstrap_status() to anon, authenticated;
grant execute on function public.create_initial_boss(text,text,text) to anon, authenticated;
grant execute on function public.admin_login(text,text) to anon, authenticated;
grant execute on function public.admin_logout(text) to anon, authenticated;
grant execute on function public.validate_admin_session(text,text) to anon, authenticated;
grant execute on function public.admin_snapshot(text) to anon, authenticated;
grant execute on function public.admin_mutate(text,text,text,jsonb) to anon, authenticated;
grant execute on function public.admin_create_user(text,text,text,text,jsonb) to anon, authenticated;
grant execute on function public.admin_set_user_active(text,uuid,boolean) to anon, authenticated;
grant execute on function public.admin_reset_user_password(text,uuid,text) to anon, authenticated;
grant execute on function public.publish_order_event(text,bigint,text) to anon, authenticated;

insert into public.toppings (id,name,kind,price,sort_order) values
('brownie','Brownie','Topping',3200,1),('queso','Queso','Topping',3200,2),('chocmelos','Chocmelos','Topping',3200,3),
('chocoramo','Chocoramo','Topping',3200,4),('quipitos','Quipitos','Topping',3200,5),('chococrispi','Chococrispi','Topping',3200,6),
('chips-chocolate','Chips de chocolate','Topping',3200,7),('mango','Mango','Topping',3200,8),('oreo','Oreo','Topping',3200,9),
('milo','Milo','Topping',3200,10),('biscolata','Biscolata','Topping',3200,11),('chocolatina-jumbo','Chocolatina Jumbo','Topping',3200,12),
('piazza','Piazza','Topping',3200,13),('chunks','Chunks','Topping',3200,14),('minichips','Minichips','Topping',3200,15),
('mani','Maní','Topping',3200,16),('klim','Klim','Topping',3200,17),
('leche-condensada','Leche condensada','Salsa',0,1),('arequipe-alpina','Arequipe Alpina','Salsa',0,2),
('frutos-rojos','Frutos rojos','Salsa',0,3),('leche-polvo','Leche en polvo','Salsa',0,4),('hersheys','Hershey''s','Salsa',0,5)
on conflict (id) do nothing;

insert into public.payment_methods (id,name,account_value,instructions,sort_order) values
('transferencia','Transferencia','','Completa los datos bancarios desde el administrador.',1),
('nequi','Nequi','','Completa el número de Nequi desde el administrador.',2),
('bre-b','Bre-B','','Completa la llave Bre-B desde el administrador.',3),
('efectivo','Efectivo','Pago contra entrega','Ten el valor exacto si es posible.',4)
on conflict (id) do nothing;

insert into public.products (id,name,category,price,image_url,description,badge,featured,sort_order,modifiers) values
('original-12','La Original · 12 oz','La Original',19900,'./images/juanelos-original.png','Cama de fresas, crema de la casa y fruta fresca. Incluye 2 salsas.','12 oz',true,1,'[{"id":"salsas","name":"Elige 2 salsas","source":"Salsa","required":true,"min":2,"max":2},{"id":"extras","name":"Toppings adicionales","source":"Topping","max":5,"usePrice":true}]'),
('original-16','La Original · 16 oz','La Original',23500,'./images/juanelos-original.png','La Original en tamaño grande. Incluye 2 salsas.','16 oz',true,2,'[{"id":"salsas","name":"Elige 2 salsas","source":"Salsa","required":true,"min":2,"max":2},{"id":"extras","name":"Toppings adicionales","source":"Topping","max":5,"usePrice":true}]'),
('poderosa-12','La Poderosa · 12 oz','La Poderosa',23900,'./images/juanelos-poderosa.png','Nuestra copa más poderosa: 1 salsa y 3 toppings.','12 oz',true,3,'[{"id":"salsas","name":"Elige 1 salsa","source":"Salsa","required":true,"min":1,"max":1},{"id":"toppings","name":"Elige 3 toppings","source":"Topping","required":true,"min":3,"max":3},{"id":"extras","name":"Toppings adicionales","source":"Topping","max":5,"usePrice":true}]'),
('poderosa-16','La Poderosa · 16 oz','La Poderosa',27900,'./images/juanelos-poderosa.png','Nuestra copa más poderosa en tamaño grande: 1 salsa y 3 toppings.','16 oz',true,4,'[{"id":"salsas","name":"Elige 1 salsa","source":"Salsa","required":true,"min":1,"max":1},{"id":"toppings","name":"Elige 3 toppings","source":"Topping","required":true,"min":3,"max":3},{"id":"extras","name":"Toppings adicionales","source":"Topping","max":5,"usePrice":true}]'),
('paye-maracuya','Paye de Maracuyá · 12 oz','Carta de Payes',18900,'./images/juanelos-payes.png','Postre de tres leches y galleta Ducal con topping de maracuyá.','',true,10,'[]'),
('paye-klim','Paye de Klim · 12 oz','Carta de Payes',18900,'./images/juanelos-payes.png','Postre de tres leches y galleta Ducal con topping de Klim.','',false,11,'[]'),
('paye-oreo','Paye de Oreo · 12 oz','Carta de Payes',18900,'./images/juanelos-payes.png','Postre de tres leches y galleta Ducal con topping de Oreo.','',true,12,'[]'),
('paye-arequipe','Paye de Arequipe · 12 oz','Carta de Payes',18900,'./images/juanelos-payes.png','Postre de tres leches y galleta Ducal con topping de arequipe.','',false,13,'[]'),
('paye-frutos-rojos','Paye de Frutos rojos · 12 oz','Carta de Payes',18900,'./images/juanelos-payes.png','Postre de tres leches y galleta Ducal con topping de frutos rojos.','',false,14,'[]'),
('paye-chocolate','Paye de Chocolate · 12 oz','Carta de Payes',21900,'./images/juanelos-payes.png','Postre de tres leches y galleta Ducal en versión de chocolate.','',true,15,'[]'),
('parfait-12','Parfait · 12 oz','Especiales',23900,'./images/juanelos-parfait.png','Yogurt griego, 3 tipos de fruta y granola artesanal.','12 oz',true,20,'[]'),
('parfait-16','Parfait · 16 oz','Especiales',27900,'./images/juanelos-parfait.png','Yogurt griego, 3 tipos de fruta y granola artesanal.','16 oz',false,21,'[]'),
('maracu-brownie-12','Maracú Brownie · 12 oz','Especiales',20900,'./images/juanelos-maracu-brownie.png','Crema de maracuyá con brownie, trozos de mango y fresa.','12 oz',true,22,'[]'),
('maracu-brownie-16','Maracú Brownie · 16 oz','Especiales',25900,'./images/juanelos-maracu-brownie.png','Crema de maracuyá con brownie, trozos de mango y fresa.','16 oz',false,23,'[]'),
('choco-cruch-12','Choco Cruch · 12 oz','Especiales',23900,'./images/juanelos-choco-cruch.png','Fresas con crema y cobertura de chocolate, Chococrispi, Biscolata y salsa Hershey''s.','12 oz',true,24,'[]'),
('choco-cruch-16','Choco Cruch · 16 oz','Especiales',28900,'./images/juanelos-choco-cruch.png','Fresas con crema y cobertura de chocolate, Chococrispi, Biscolata y salsa Hershey''s.','16 oz',false,25,'[]'),
('fres-helada-12','Fres helada · 12 oz','Especiales',24500,'./images/juanelos-fresas.png','Fresas con crema, queso cremoso, bola de helado y salsa de chocolate Hershey''s.','12 oz',true,26,'[]'),
('fres-helada-16','Fres helada · 16 oz','Especiales',29500,'./images/juanelos-fresas.png','Fresas con crema, queso cremoso, bola de helado y salsa de chocolate Hershey''s.','16 oz',false,27,'[]'),
('fresas-chocolate','Fresas con Chocolate · 12 oz','Especiales',25500,'./images/juanelos-fresas.png','Fresas enteras cubiertas de chocolate.','12 oz',true,28,'[]'),
('soda-saborizada','Soda saborizada · 22 oz','Bebidas',12000,'./images/juanelos-bebidas.png','Soda fría saborizada.','',false,30,'[]'),
('agua','Botella de agua','Bebidas',5000,'./images/juanelos-bebidas.png','Agua embotellada.','',false,31,'[]'),
('soda-sencilla','Soda sencilla','Bebidas',5000,'./images/juanelos-bebidas.png','Soda fría sencilla.','',false,32,'[]'),
('americano','Americano','Bebidas',5000,'./images/juanelos-bebidas.png','Café americano.','',false,33,'[]'),
('frappe-cafe','Frappé Café · 22 oz','Bebidas',14000,'./images/juanelos-bebidas.png','Frappé de café.','',false,34,'[]'),
('frappe-casa','Frappé de la casa · 22 oz','Bebidas',12000,'./images/juanelos-bebidas.png','Frappé especial de la casa.','',true,35,'[]')
on conflict (id) do nothing;

do $$
begin
  alter publication supabase_realtime add table public.products;
exception when duplicate_object then null;
end $$;
do $$
begin
  alter publication supabase_realtime add table public.toppings;
exception when duplicate_object then null;
end $$;
do $$
begin
  alter publication supabase_realtime add table public.payment_methods;
exception when duplicate_object then null;
end $$;
do $$
begin
  alter publication supabase_realtime add table public.neighborhoods;
exception when duplicate_object then null;
end $$;
do $$
begin
  alter publication supabase_realtime add table public.order_events;
exception when duplicate_object then null;
end $$;
